[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
limine = "0.1.9"
raw-cpuid = "10.6.0"
spin = "0.9.4"
x86_64 = { path = "../x86_64" }