[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
limine = { git = "https://github.com/limine-bootloader/limine-rs/" }
num-derive = "0.3.3"
raw-cpuid = "10.6.0"
spin = "0.9.4"
x86_64 = { path = "../x86_64" }
bitfield = "0.14.0"

[dependencies.num-traits]
version = "0.2"
default-features = false 
